module.exports = {
  apps: [
    {
      name: "warp-bridge",
      script: "uv",
      cwd: "/Users/xiongfeng/Documents/Web3Projects/warp2api",
      interpreter: "none",
      args: "run warp2api-bridge --port 28888",
      watch: ["src", "server.py"],
      ignore_watch: [".git", ".venv", "logs", "__pycache__", "*.log"],
      watch_delay: 1200,
      autorestart: true,
      max_restarts: 50,
      min_uptime: "5s",
      out_file: "logs/pm2_warp_bridge_out.log",
      error_file: "logs/pm2_warp_bridge_err.log",
      merge_logs: true,
      env: {
        PYTHONUNBUFFERED: "1",
        WARP_TRUST_ENV: "0",
      },
    },
    {
      name: "warp-openai",
      script: "uv",
      cwd: "/Users/xiongfeng/Documents/Web3Projects/warp2api",
      interpreter: "none",
      args: "run warp2api-openai --port 28889",
      watch: ["src", "openai_compat.py"],
      ignore_watch: [".git", ".venv", "logs", "__pycache__", "*.log"],
      watch_delay: 1200,
      autorestart: true,
      max_restarts: 50,
      min_uptime: "5s",
      out_file: "logs/pm2_warp_openai_out.log",
      error_file: "logs/pm2_warp_openai_err.log",
      merge_logs: true,
      env: {
        PYTHONUNBUFFERED: "1",
        WARP_BRIDGE_URL: "http://127.0.0.1:28888",
      },
    },
    {
      name: "warp-log-watchdog",
      script: "scripts/pm2_log_watchdog.sh",
      cwd: "/Users/xiongfeng/Documents/Web3Projects/warp2api",
      interpreter: "bash",
      watch: false,
      autorestart: true,
      max_restarts: 1000,
      min_uptime: "2s",
      out_file: "logs/pm2_watchdog_out.log",
      error_file: "logs/pm2_watchdog_err.log",
      merge_logs: true,
      env: {
        WATCH_INTERVAL_SECONDS: "20",
      },
    },
  ],
};
